# Generated by Django 4.0.6 on 2022-09-08 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addressbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Message date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addressbook.person', verbose_name='Chat under person')),
            ],
        ),
    ]
